### ISSUE TITLE
Cannot install on Odoo 14

### ISSUE THREAD

**Issue by danieledraganti** [obayit/odoo_dhtmlxgantt#14]
Hello,
I downloaded the latest version of your app (14.1) but I get the following stack trace when trying to install it on Odoo Community 14.0. Any ideas on how to solve it? Thanks in advance.

```
Errore:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 347, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 912, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 531, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1393, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1381, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-71>", line 2, in button_immediate_install
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 73, in check_and_log
    return method(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 474, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 592, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 455, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 348, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 197, in load_module_graph
    registry.setup_models(cr)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 273, in setup_models
    model._setup_base()
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 2791, in _setup_base
    self._add_field(name, field.new())
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 404, in _add_field
    field.setup_base(self, name)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 278, in setup_base
    self._setup_attrs(model, name)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 2328, in _setup_attrs
    "containing the specified option." % self
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: ir.actions.act_window.view.view_mode: required selection fields must define an ondelete policy that implements the proper cleanup of the corresponding records upon module uninstallation. Please use one or more of the following policies: 'set default' (if the field has a default defined), 'cascade', or a single-argument callable where the argument is the recordset containing the specified option.
```

**Comment by zm14** [comment]
Hi,
I have simillar error when i install this version:
```
Error:


Traceback:
Error: QWeb2: Template 'dhx_gantt.gantt_view' not found
    at Object.exception (http://localhost:8069/web/content/116-f7a39cd/web.assets_common.js:4388:7)
    at Engine._render (http://localhost:8069/web/content/116-f7a39cd/web.assets_common.js:4433:103)
    at Engine.render (http://localhost:8069/web/content/116-f7a39cd/web.assets_common.js:4429:151)
    at Class.renderElement (http://localhost:8069/web/content/116-f7a39cd/web.assets_common.js:4944:734)
    at http://localhost:8069/web/content/116-f7a39cd/web.assets_common.js:4954:6
    at async Promise.all (index 1)
    at async Promise.all (index 0)
    at async Class.start (http://localhost:8069/web/content/215-dfb3d51/web.assets_backend.js:1334:1)``
```

**Comment by obayit** [comment]
@zm14 maybe you just need to regenerate assets

**Comment by zm14** [comment]
> @zm14 maybe you just need to regenerate assets

I tried that but still the same error

**Comment by bogdan-harja** [comment]
Hi! I'm also having the below error when trying to install this module's latest version on Odoo Community 14. Any ideas, please?

Error:
Odoo Server Error

Traceback (most recent call last):
  File "C:\Program Files\Odoo 14.0.20211102\server\odoo\tools\convert.py", line 677, in _tag_root
    f(rec)
  File "C:\Program Files\Odoo 14.0.20211102\server\odoo\tools\convert.py", line 580, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "C:\Program Files\Odoo 14.0.20211102\server\odoo\models.py", line 4212, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "C:\Program Files\Odoo 14.0.20211102\server\odoo\models.py", line 4141, in _load_records_create
    return self.create(values)
  File "<decorator-gen-42>", line 2, in create
  File "C:\Program Files\Odoo 14.0.20211102\server\odoo\api.py", line 345, in _model_create_multi
    return create(self, arg)
  File "C:\Program Files\Odoo 14.0.20211102\server\odoo\addons\base\models\ir_ui_view.py", line 482, in create
    return super(View, self).create(vals_list)
  File "<decorator-gen-64>", line 2, in create
  File "C:\Program Files\Odoo 14.0.20211102\server\odoo\api.py", line 345, in _model_create_multi
    return create(self, arg)
  File "C:\Program Files\Odoo 14.0.20211102\server\odoo\addons\base\models\ir_fields.py", line 534, in create
    recs = super().create(vals_list)
  File "<decorator-gen-13>", line 2, in create
  File "C:\Program Files\Odoo 14.0.20211102\server\odoo\api.py", line 345, in _model_create_multi
    return create(self, arg)
  File "C:\Program Files\Odoo 14.0.20211102\server\odoo\models.py", line 3902, in create
    fields[0].determine_inverse(batch_recs)
  File "C:\Program Files\Odoo 14.0.20211102\server\odoo\fields.py", line 1187, in determine_inverse
    getattr(records, self.inverse)()
  File "C:\Program Files\Odoo 14.0.20211102\server\odoo\addons\base\models\ir_ui_view.py", line 300, in _inverse_arch
    view.write(data)
  File "C:\Program Files\Odoo 14.0.20211102\server\odoo\addons\base\models\ir_ui_view.py", line 500, in write
    res = super(View, self).write(self._compute_defaults(vals))
  File "C:\Program Files\Odoo 14.0.20211102\server\odoo\models.py", line 3686, in write
    real_recs._validate_fields(vals, inverse_fields)
  File "C:\Program Files\Odoo 14.0.20211102\server\odoo\models.py", line 1266, in _validate_fields
    check(self)
  File "C:\Program Files\Odoo 14.0.20211102\server\odoo\addons\base\models\ir_ui_view.py", line 411, in _check_xml
    )).with_traceback(e.__traceback__) from None
  File "C:\Program Files\Odoo 14.0.20211102\server\odoo\addons\base\models\ir_ui_view.py", line 391, in _check_xml
    view.postprocess_and_fields(view_doc, validate=True)
  File "C:\Program Files\Odoo 14.0.20211102\server\odoo\addons\base\models\ir_ui_view.py", line 851, in postprocess_and_fields
    arch, name_manager = self._postprocess_view(node, model, validate=validate)
  File "C:\Program Files\Odoo 14.0.20211102\server\odoo\addons\base\models\ir_ui_view.py", line 863, in _postprocess_view
    self.postprocess(node, [], editable, name_manager)
  File "C:\Program Files\Odoo 14.0.20211102\server\odoo\addons\base\models\ir_ui_view.py", line 963, in postprocess
    self.postprocess(child, current_node_path, node_info['editable'], name_manager)
  File "C:\Program Files\Odoo 14.0.20211102\server\odoo\addons\base\models\ir_ui_view.py", line 963, in postprocess
    self.postprocess(child, current_node_path, node_info['editable'], name_manager)
  File "C:\Program Files\Odoo 14.0.20211102\server\odoo\addons\base\models\ir_ui_view.py", line 963, in postprocess
    self.postprocess(child, current_node_path, node_info['editable'], name_manager)
  [Previous line repeated 1 more time]
  File "C:\Program Files\Odoo 14.0.20211102\server\odoo\addons\base\models\ir_ui_view.py", line 942, in postprocess
    postprocessor(node, name_manager, node_info)
  File "C:\Program Files\Odoo 14.0.20211102\server\odoo\addons\base\models\ir_ui_view.py", line 1003, in _postprocess_tag_field
    editable=node_info['editable'],
  File "C:\Program Files\Odoo 14.0.20211102\server\odoo\addons\base\models\ir_ui_view.py", line 863, in _postprocess_view
    self.postprocess(node, [], editable, name_manager)
  File "C:\Program Files\Odoo 14.0.20211102\server\odoo\addons\base\models\ir_ui_view.py", line 963, in postprocess
    self.postprocess(child, current_node_path, node_info['editable'], name_manager)
  File "C:\Program Files\Odoo 14.0.20211102\server\odoo\addons\base\models\ir_ui_view.py", line 954, in postprocess
    validator(node, name_manager, node_info)
  File "C:\Program Files\Odoo 14.0.20211102\server\odoo\addons\base\models\ir_ui_view.py", line 1090, in _validate_tag_field
    self.handle_view_error(msg)
  File "C:\Program Files\Odoo 14.0.20211102\server\odoo\addons\base\models\ir_ui_view.py", line 673, in handle_view_error
    raise ValueError(formatted_message).with_traceback(from_traceback) from from_exception
odoo.exceptions.ValidationError: Error while validating view:

Field "name" does not exist in model "project.depending.tasks"

View name: project.task.gant.data.form
Error context:
 view: ir.ui.view(1133,)
 xmlid: view_task_gantt_data_form
 view.model: project.task
 view.parent: ir.ui.view(993,)
 file: c:\program files\odoo 14.0.20211102\server\odoo\addons\dhx_gantt\views\task_views.xml


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Program Files\Odoo 14.0.20211102\server\odoo\addons\base\models\ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "C:\Program Files\Odoo 14.0.20211102\server\odoo\http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "C:\Program Files\Odoo 14.0.20211102\server\odoo\http.py", line 360, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "C:\Program Files\Odoo 14.0.20211102\server\odoo\service\model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "C:\Program Files\Odoo 14.0.20211102\server\odoo\http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "C:\Program Files\Odoo 14.0.20211102\server\odoo\http.py", line 913, in __call__
    return self.method(*args, **kw)
  File "C:\Program Files\Odoo 14.0.20211102\server\odoo\http.py", line 532, in response_wrap
    response = f(*args, **kw)
  File "C:\Program Files\Odoo 14.0.20211102\server\odoo\addons\web\controllers\main.py", line 1393, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "C:\Program Files\Odoo 14.0.20211102\server\odoo\addons\web\controllers\main.py", line 1381, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "C:\Program Files\Odoo 14.0.20211102\server\odoo\api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "C:\Program Files\Odoo 14.0.20211102\server\odoo\api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-71>", line 2, in button_immediate_install
  File "C:\Program Files\Odoo 14.0.20211102\server\odoo\addons\base\models\ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "C:\Program Files\Odoo 14.0.20211102\server\odoo\addons\base\models\ir_module.py", line 475, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "C:\Program Files\Odoo 14.0.20211102\server\odoo\addons\base\models\ir_module.py", line 593, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "C:\Program Files\Odoo 14.0.20211102\server\odoo\modules\registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "C:\Program Files\Odoo 14.0.20211102\server\odoo\modules\loading.py", line 461, in load_modules
    loaded_modules, update_module, models_to_check)
  File "C:\Program Files\Odoo 14.0.20211102\server\odoo\modules\loading.py", line 349, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "C:\Program Files\Odoo 14.0.20211102\server\odoo\modules\loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package)
  File "C:\Program Files\Odoo 14.0.20211102\server\odoo\modules\loading.py", line 69, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "C:\Program Files\Odoo 14.0.20211102\server\odoo\tools\convert.py", line 733, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate)
  File "C:\Program Files\Odoo 14.0.20211102\server\odoo\tools\convert.py", line 799, in convert_xml_import
    obj.parse(doc.getroot())
  File "C:\Program Files\Odoo 14.0.20211102\server\odoo\tools\convert.py", line 719, in parse
    self._tag_root(de)
  File "C:\Program Files\Odoo 14.0.20211102\server\odoo\tools\convert.py", line 677, in _tag_root
    f(rec)
  File "C:\Program Files\Odoo 14.0.20211102\server\odoo\tools\convert.py", line 685, in _tag_root
    )) from e
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Program Files\Odoo 14.0.20211102\server\odoo\http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "C:\Program Files\Odoo 14.0.20211102\server\odoo\http.py", line 316, in _handle_exception
    raise exception.with_traceback(None) from new_cause
odoo.tools.convert.ParseError: while parsing file:/c:/program%20files/odoo%2014.0.20211102/server/odoo/addons/dhx_gantt/views/task_views.xml:21, near
<record id="view_task_gantt_data_form" model="ir.ui.view">
            <field name="name">project.task.gant.data.form</field>
            <field name="model">project.task</field>
            <field name="inherit_id" ref="project.view_task_form2"/>
            <field name="arch" type="xml">

                <xpath expr="//page[@name='description_page']" position="after">
                    <page string="Dependencies">
                        <group string="Gantt Info">
                            <field name="date_start"/>
                            <field name="date_end"/>
                            <field name="planned_duration"/>
                        </group>
                        <separator string="Predecessors"/>
                        <field name="dependency_task_ids">
                            <tree editable="buttom">
                                <field name="project_id" invisible="1"/>
                                <field name="task_id" domain="[('project_id', '=', project_id), ('id', '!=', parent.id)]"/>
                                <field name="relation_type"/>
                            </tree>
                        </field>
                        <separator string="Successors"/>
                        <field name="depending_task_ids">
                            <tree editable="buttom">
                                <field name="project_id" invisible="1"/>
                                <field name="depending_task_id" domain="[('project_id', '=', project_id), ('id', '!=', parent.id)]"/>
                                <field name="relation_type"/>
                            </tree>
                        </field>
                    </page>
                </xpath>
            </field>
        </record>

**Comment by angelocorreia27** [comment]
> Hi, I have simillar error when i install this version:
> 
> ```
> Error:
> 
> 
> Traceback:
> Error: QWeb2: Template 'dhx_gantt.gantt_view' not found
>     at Object.exception (http://localhost:8069/web/content/116-f7a39cd/web.assets_common.js:4388:7)
>     at Engine._render (http://localhost:8069/web/content/116-f7a39cd/web.assets_common.js:4433:103)
>     at Engine.render (http://localhost:8069/web/content/116-f7a39cd/web.assets_common.js:4429:151)
>     at Class.renderElement (http://localhost:8069/web/content/116-f7a39cd/web.assets_common.js:4944:734)
>     at http://localhost:8069/web/content/116-f7a39cd/web.assets_common.js:4954:6
>     at async Promise.all (index 1)
>     at async Promise.all (index 0)
>     at async Class.start (http://localhost:8069/web/content/215-dfb3d51/web.assets_backend.js:1334:1)``
> ```

Same error with me.

**Comment by obayit** [comment]
I am closing this because I couldn't replicate these errors in 14.0

**Comment by thiepwong** [comment]
And how to resolve it?
