### ISSUE TITLE
Error during installation - field name does not exist (odoo12)

### ISSUE THREAD

**Issue by jonesluster** [obayit/odoo_dhtmlxgantt#3]
Your work looks very promising. I received this error during an installation attempt on Community Odoo 12.  After this error text I'll also include a list of installed apps / modules.

Any ideas?  

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo12/odoo/odoo/models.py", line 1108, in _validate_fields
    check(self)
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_ui_view.py", line 351, in _check_xml
    self.postprocess_and_fields(view.model, view_doc, view.id)
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_ui_view.py", line 1094, in postprocess_and_fields
    fields_def = self.postprocess(model, node, view_id, False, fields)
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_ui_view.py", line 919, in postprocess
    fields.update(self.postprocess(model, f, view_id, in_tree_view, model_fields))
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_ui_view.py", line 919, in postprocess
    fields.update(self.postprocess(model, f, view_id, in_tree_view, model_fields))
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_ui_view.py", line 919, in postprocess
    fields.update(self.postprocess(model, f, view_id, in_tree_view, model_fields))
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_ui_view.py", line 879, in postprocess
    ).postprocess_and_fields(field.comodel_name, f, view_id)
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_ui_view.py", line 1106, in postprocess_and_fields
    self.raise_view_error(message, view_id)
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_ui_view.py", line 548, in raise_view_error
    raise ValueError(message)
ValueError: Field `name` does not exist

Error context:
View `project.task.gant.data.form`
[view_id: 1621, xml_id: n/a, model: project.task, parent_id: 541]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo12/odoo/odoo/tools/convert.py", line 758, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/odoo12/odoo/odoo/tools/convert.py", line 663, in _tag_record
    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
  File "/opt/odoo12/odoo/odoo/models.py", line 3871, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/opt/odoo12/odoo/addons/website/models/ir_ui_view.py", line 129, in _load_records_create
    records = super(View, self)._load_records_create(values)
  File "/opt/odoo12/odoo/odoo/models.py", line 3785, in _load_records_create
    return self.create(values)
  File "<decorator-gen-32>", line 2, in create
  File "/opt/odoo12/odoo/odoo/api.py", line 452, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_ui_view.py", line 428, in create
    return super(View, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/opt/odoo12/odoo/odoo/api.py", line 452, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo12/odoo/odoo/models.py", line 3602, in create
    fields[0].determine_inverse(batch_recs)
  File "/opt/odoo12/odoo/odoo/fields.py", line 1117, in determine_inverse
    getattr(records, self.inverse)()
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_ui_view.py", line 275, in _inverse_arch
    view.write(data)
  File "/opt/odoo12/odoo/addons/website/models/ir_ui_view.py", line 41, in write
    return super(View, self).write(vals)
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_ui_view.py", line 444, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/opt/odoo12/odoo/odoo/models.py", line 3327, in write
    self._write(store_vals)
  File "/opt/odoo12/odoo/odoo/models.py", line 3463, in _write
    self._validate_fields(vals)
  File "/opt/odoo12/odoo/odoo/models.py", line 1112, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.exceptions.ValidationError: ('Error while validating constraint\n\nField `name` does not exist\n\nError context:\nView `project.task.gant.data.form`\n[view_id: 1621, xml_id: n/a, model: project.task, parent_id: 541]', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo12/odoo/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo12/odoo/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo12/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo12/odoo/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo12/odoo/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo12/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo12/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo12/odoo/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo12/odoo/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo12/odoo/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo12/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo12/odoo/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo12/odoo/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-61>", line 2, in button_immediate_install
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_module.py", line 445, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_module.py", line 561, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/odoo12/odoo/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo12/odoo/odoo/modules/loading.py", line 421, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/opt/odoo12/odoo/odoo/modules/loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/opt/odoo12/odoo/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/opt/odoo12/odoo/odoo/modules/loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/opt/odoo12/odoo/odoo/tools/convert.py", line 802, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/odoo12/odoo/odoo/tools/convert.py", line 865, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/odoo12/odoo/odoo/tools/convert.py", line 755, in parse
    self.parse(rec, mode)
  File "/opt/odoo12/odoo/odoo/tools/convert.py", line 764, in parse
    exc_info[2]
  File "/opt/odoo12/odoo/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/opt/odoo12/odoo/odoo/tools/convert.py", line 758, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/odoo12/odoo/odoo/tools/convert.py", line 663, in _tag_record
    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
  File "/opt/odoo12/odoo/odoo/models.py", line 3871, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/opt/odoo12/odoo/addons/website/models/ir_ui_view.py", line 129, in _load_records_create
    records = super(View, self)._load_records_create(values)
  File "/opt/odoo12/odoo/odoo/models.py", line 3785, in _load_records_create
    return self.create(values)
  File "<decorator-gen-32>", line 2, in create
  File "/opt/odoo12/odoo/odoo/api.py", line 452, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_ui_view.py", line 428, in create
    return super(View, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/opt/odoo12/odoo/odoo/api.py", line 452, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo12/odoo/odoo/models.py", line 3602, in create
    fields[0].determine_inverse(batch_recs)
  File "/opt/odoo12/odoo/odoo/fields.py", line 1117, in determine_inverse
    getattr(records, self.inverse)()
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_ui_view.py", line 275, in _inverse_arch
    view.write(data)
  File "/opt/odoo12/odoo/addons/website/models/ir_ui_view.py", line 41, in write
    return super(View, self).write(vals)
  File "/opt/odoo12/odoo/odoo/addons/base/models/ir_ui_view.py", line 444, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/opt/odoo12/odoo/odoo/models.py", line 3327, in write
    self._write(store_vals)
  File "/opt/odoo12/odoo/odoo/models.py", line 3463, in _write
    self._validate_fields(vals)
  File "/opt/odoo12/odoo/odoo/models.py", line 1112, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.tools.convert.ParseError: "Error while validating constraint

Field `name` does not exist

Error context:
View `project.task.gant.data.form`
[view_id: 1621, xml_id: n/a, model: project.task, parent_id: 541]
None" while parsing /opt/odoo12/odoo-custom-addons/dhx_gantt/views/task_views.xml:21, near
<record id="view_task_gantt_data_form" model="ir.ui.view">
            <field name="name">project.task.gant.data.form</field>
            <field name="model">project.task</field>
            <field name="inherit_id" ref="project.view_task_form2"/>
            <field name="arch" type="xml">
                <data><xpath expr="//field[@name='user_id']" position="after">
                    <field name="planned_duration"/>
                    <field name="lag_time"/>
                </xpath>
                <xpath expr="//page[@name='description_page']" position="after">
                    <page string="Dependencies">
                        <separator string="Predecessors"/>
                        <field name="dependency_task_ids">
                            <tree editable="buttom">
                                <field name="project_id" invisible="1"/>
                                <field name="task_id" domain="[('project_id', '=', project_id)]"/>
                                <field name="relation_type"/>
                            </tree>
                        </field>
                        <separator string="Successors"/>
                        <field name="depending_task_ids">
                            <tree editable="buttom">
                                <field name="project_id" invisible="1"/>
                                <field name="depending_task_id" domain="[('project_id', '=', project_id)]"/>
                                <field name="relation_type"/>
                            </tree>
                        </field>
                    </page>
                </xpath>
            </data></field>
        </record>

Installed Apps / Modules

Module   Name | Technical Name | Author | Website | Version
-- | -- | -- | -- | --
Website | website | Odoo S.A. | https://www.odoo.com/page/website-builder | 12.0.1.0
​ |   |   |   |  
Project | project | Odoo S.A. | https://www.odoo.com/page/project-management | 12.0.1.1
​ |   |   |   |  
Inventory | stock | Odoo S.A. | https://www.odoo.com/page/warehouse | 12.0.1.1
​ |   |   |   |  
Invoicing | account | Odoo S.A. | https://www.odoo.com/page/billing | 12.0.1.1
​ |   |   |   |  
Manufacturing | mrp | Odoo S.A. | https://www.odoo.com/page/manufacturing | 12.0.2.0
​ |   |   |   |  
WMS Accounting | stock_account | Odoo S.A. |   | 12.0.1.1
​ |   |   |   |  
Sales | sale_management | Odoo S.A. | https://www.odoo.com/page/sales | 12.0.1.0
​ |   |   |   |  
Task Logs | hr_timesheet | Odoo S.A. | https://www.odoo.com/page/timesheet-mobile-app | 12.0.1.0
​ |   |   |   |  
Purchase | purchase | Odoo S.A. | https://www.odoo.com/page/purchase | 12.0.1.2
​ |   |   |   |  
Purchase Stock | purchase_stock | Odoo S.A. |   | 12.0.1.2
​ |   |   |   |  
Employees | hr | Odoo S.A. | https://www.odoo.com/page/employees | 12.0.1.1
​ |   |   |   |  
Account Bank Statement Import | account_bank_statement_import | Odoo S.A. |   | 12.0.1.0
​ |   |   |   |  
Import Vendor Bills From XML | account_facturx | Odoo S.A. |   | 12.0.1.0
​ |   |   |   |  
Analytic Accounting | analytic | Odoo S.A. |   | 12.0.1.1
​ |   |   |   |  
Signup | auth_signup | Odoo S.A. |   | 12.0.1.0
​ |   |   |   |  
Barcode | barcodes | Odoo S.A. |   | 12.0.2.0
​ |   |   |   |  
Base | base | Odoo S.A. |   | 12.0.1.3
​ |   |   |   |  
Base import | base_import | Odoo S.A. |   | 12.0.1.0
​ |   |   |   |  
Initial Setup Tools | base_setup | Odoo S.A. |   | 12.0.1.0
​ |   |   |   |  
Dashboards | board | Odoo S.A. |   | 12.0.1.0
​ |   |   |   |  
IM Bus | bus | Odoo S.A. |   | 12.0.1.0
​ |   |   |   |  
Contacts | contacts | Odoo S.A. |   | 12.0.1.0
​ |   |   |   |  
Decimal Precision Configuration | decimal_precision | Odoo S.A. |   | 12.0.0.1
​ |   |   |   |  
KPI Digests | digest | Odoo S.A. |   | 12.0.1.0
​ |   |   |   |  
Document Page | document_page | OpenERP SA, Odoo Community Association (OCA) | https://github.com/OCA/knowledge | 12.0.1.1.0
​ |   |   |   |  
Document Page Project | document_page_project | Eficent, Odoo Community Association (OCA) | https://github.com/OCA/knowledge | 12.0.1.0.0
​ |   |   |   |  
Email Gateway | fetchmail | Odoo S.A. |   | 12.0.1.0
​ |   |   |   |  
In-App Purchases | iap | Odoo S.A. |   | 12.0.1.0
​ |   |   |   |  
OdooBot for livechat | im_livechat_mail_bot | Odoo S.A. | https://www.odoo.com/page/discuss | 12.0.1.0
​ |   |   |   |  
Knowledge | knowledge | OpenERP SA,MONK Software, Tecnativa, Eficent, Odoo Community Association   (OCA) | https://github.com/OCA/knowledge | 12.0.1.0.0
​ |   |   |   |  
Generic - Accounting | l10n_generic_coa | Odoo S.A. |   | 12.0.1.1
​ |   |   |   |  
United States - Accounting | l10n_us | Odoo S.A. |   | 12.0.1.1
​ |   |   |   |  
Discuss | mail | Odoo S.A. | https://www.odoo.com/page/discuss | 12.0.1.0
​ |   |   |   |  
OdooBot | mail_bot | Odoo S.A. | https://www.odoo.com/page/discuss | 12.0.1.0
​ |   |   |   |  
Partner Autocomplete | partner_autocomplete | Odoo SA |   | 12.0.1.0
​ |   |   |   |  
Payment Acquirer | payment | Odoo S.A. |   | 12.0.1.0
​ |   |   |   |  
Transfer Payment Acquirer | payment_transfer | Odoo S.A. |   | 12.0.1.0
​ |   |   |   |  
Just In Time Scheduling | procurement_jit | Odoo S.A. |   | 12.0.1.0
​ |   |   |   |  
Products & Pricelists | product | Odoo S.A. |   | 12.0.1.2
​ |   |   |   |  
Products Expiration Date | product_expiry | Odoo S.A. |   | 12.0.1.0
​ |   |   |   |  
Project Types | project_category | ADHOC SA,Tecnativa, Onestein, Odoo Community Association (OCA) | https://github.com/OCA/project | 12.0.1.0.0
​ |   |   |   |  
Project Description | project_description | Tecnativa, C2i Change 2 improve, Odoo Community Association (OCA) | https://github.com/OCA/project | 12.0.1.0.0
​ |   |   |   |  
Project key | project_key | Modoolar, Odoo Community Association (OCA) | https://github.com/OCA/project/ | 12.0.1.0.0
​ |   |   |   |  
Projects List View | project_list | Brainbean Apps, Odoo Community Association (OCA) | https://github.com/OCA/project | 12.0.1.0.0
​ |   |   |   |  
Project Milestones | project_milestone | Patrick Wilson, Odoo Community Association (OCA) | https://github.com/OCA/project | 12.0.1.0.0
​ |   |   |   |  
Project Parent Task Filter | project_parent_task_filter | C2i Change 2 improve, Odoo Community Association (OCA) | https://github.com/OCA/project | 12.0.1.2.0
​ |   |   |   |  
Project Roles | project_role | Brainbean Apps, Odoo Community Association (OCA) | https://github.com/OCA/project | 12.0.2.0.0
​ |   |   |   |  
Project Task Stage Closed | project_stage_closed | ACSONE SA/NV,Tecnativa,Odoo Community Association (OCA) | https://github.com/OCA/project | 12.0.1.0.0
​ |   |   |   |  
Add State field to Project Stages | project_stage_state | Daniel Reis,Odoo Community Association (OCA) | https://github.com/OCA/project | 12.0.1.0.0
​ |   |   |   |  
Project Status | project_status | Patrick Wilson, Odoo Community Association (OCA) | https://github.com/OCA/project | 12.0.1.1.0
​ |   |   |   |  
Project Tags | project_tag | Patrick Wilson, Odoo Community Association (OCA) | https://github.com/OCA/project | 12.0.1.0.0
​ |   |   |   |  
Sequential Code for Tasks | project_task_code | OdooMRP team, AvanzOSC, Tecnativa, Odoo Community Association (OCA) | https://github.com/OCA/project | 12.0.1.0.1
​ |   |   |   |  
Project Task Default Stage | project_task_default_stage | Tecnativa, Odoo Community Association (OCA) | https://github.com/OCA/project | 12.0.1.0.0
​ |   |   |   |  
Project Task Dependencies | project_task_dependency | Onestein,Odoo Community Association (OCA) | https://github.com/OCA/project | 12.0.1.0.0
​ |   |   |   |  
Project Templates | project_template | Patrick Wilson, Odoo Community Association (OCA) | https://github.com/OCA/project | 12.0.1.0.0
​ |   |   |   |  
Project Template & Milestone | project_template_milestone | Patrick Wilson, Odoo Community Association (OCA) | https://github.com/OCA/project | 12.0.1.0.0
​ |   |   |   |  
Project timeline | project_timeline | Tecnativa, Onestein, Odoo Community Association (OCA) | https://github.com/OCA/project | 12.0.1.2.0
​ |   |   |   |  
Project Timeline - Timesheet | project_timeline_hr_timesheet | Onestein, Odoo Community Association (OCA) | https://github.com/OCA/project | 12.0.1.0.1
​ |   |   |   |  
Project Timeline Task Dependencies | project_timeline_task_dependency | Onestein, Odoo Community Association (OCA) | https://github.com/oca/project | 12.0.1.0.0
​ |   |   |   |  
Purchase and MRP Management | purchase_mrp | Odoo S.A. |   | 12.0.1.0
​ |   |   |   |  
Customer Rating | rating | Odoo S.A. |   | 12.0.1.0
​ |   |   |   |  
Resource | resource | Odoo S.A. |   | 12.0.1.1
​ |   |   |   |  
Sales | sale | Odoo S.A. |   | 12.0.1.1
​ |   |   |   |  
Sales and MRP Management | sale_mrp | Odoo S.A. |   | 12.0.1.0
​ |   |   |   |  
Sale Purchase | sale_purchase | Odoo S.A. | https://www.odoo.com/ | 12.0.1.0
​ |   |   |   |  
Sales and Warehouse Management | sale_stock | Odoo S.A. |   | 12.0.1.0
​ |   |   |   |  
Sales Timesheet | sale_timesheet | Odoo S.A. |   | 12.0.1.0
​ |   |   |   |  
Sales Teams | sales_team | Odoo S.A. | https://www.odoo.com/page/crm | 12.0.1.0
​ |   |   |   |  
SMS gateway | sms | Odoo S.A. |   | 12.0.1.0
​ |   |   |   |  
Snail Mail | snailmail | Odoo S.A. |   | 12.0.0.1
​ |   |   |   |  
snailmail_account | snailmail_account | Odoo S.A. |   | 12.0.0.1
​ |   |   |   |  
social_media | social_media | Odoo S.A. |   | 12.0.0.1
​ |   |   |   |  
Stock Barcodes | stock_barcodes | Tecnativa, Odoo Community Association (OCA) | https://odoo-community.org/ | 12.0.11.0.1.0.0
​ |   |   |   |  
Units of measure | uom | Odoo S.A. |   | 12.0.1.0
​ |   |   |   |  
Web | web | Odoo S.A. |   | 12.0.1.0
​ |   |   |   |  
Odoo Web Diagram | web_diagram | Odoo S.A. |   | 12.0.2.0
​ |   |   |   |  
Web Editor | web_editor | Odoo S.A. |   | 12.0.1.0
​ |   |   |   |  
Gauge Widget for Kanban | web_kanban_gauge | Odoo S.A. |   | 12.0.1.0
​ |   |   |   |  
Odoo Settings Dashboard | web_settings_dashboard | Odoo S.A. |   | 12.0.1.0
​ |   |   |   |  
Web timeline | web_timeline | ACSONE SA/NV, Tecnativa, Monk Software, Onestein, Odoo Community   Association (OCA) | https://github.com/OCA/web | 12.0.1.0.5

**Comment by obayit** [comment]
Is this still an issue?
reproducing this is not easy, but I will try!

**Comment by ivosm** [comment]
I have same or very similar issue, i.e. 
ValueError: Pole  `name` neexistuje  
│Error context:
│View `project.task.gant.data.form`   
│[view_id: 2584, xml_id: n/a, model: project.task, parent_id: 657] 
Second attempt to install went through with error like 
"bad query: b"SELECT MAX(CASE WHEN perm_read THEN 1 ELSE 0 END)" or can't not load demo data ... 
shows diagram but produces error for reschedule 
self.date_start = datetime.datetime.combine(self.project_id.date_start, datetime.time.min)
TypeError: combine() argument 1 must be datetime.date, not bool

If you have still problem to reproduce it, let me know and we can go in sync step by step.

**Comment by obayit** [comment]
Stupid me, I forgot to remove the demo line from the manifest. (in enterprise version it just raises a warning)
Also fixed the rescheduling error.
commit  [here](https://github.com/obayit/odoo_dhtmlxgantt/commit/f54a35ba90be42967cdd423e830823981be75f67)
